/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GroupRuler;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Scanner;


import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;

public class App {
    public static void main(String[] args) {

        ArrayList<Student> roster = new ArrayList<>();
        Scanner in = new Scanner(System.in);

        while (true) {
            //Print menu
            System.out.println("What would you like to do? ");
            System.out.println("1. Add student");
            System.out.println("2. Edit student");
            System.out.println("3. Print roster");
            System.out.println();

            String response = in.nextLine();

            switch (response) {

                case "1":

                    System.out.println("Please enter the students first name: ");
                    String firstName = in.nextLine();
                    System.out.println("Please enter the student's last name: ");
                    String lastName = in.nextLine();
                    System.out.println("Please enter the student's grade level: ");
                    int grade = Integer.parseInt(in.nextLine());
                    System.out.println();

                    Student s = new Student(firstName, lastName, grade);
                    s.print();
                    roster.add(s);


                case "2":

                case "3":
                    roster.forEach((student) -> student.print());

                default:
            }

        }
    }
}
